spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    primary:
      jdbc-url: jdbc:postgresql://localhost:2346/postgres14_db
      username: user14
      password: password14
      driver-class-name: org.postgresql.Driver
    secondary:
      jdbc-url: jdbc:postgresql://localhost:2347/postgres16_db
      username: user16
      password: password16
      driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
